# ── Server ──────────────────────────────────────────────────────────────────
server.port=9090

# ── PostgreSQL ───────────────────────────────────────────────────────────────
spring.datasource.url=jdbc:postgresql://localhost:5432/activites_sociales
spring.datasource.username=tt_user
spring.datasource.password=tt_password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ── MongoDB ──────────────────────────────────────────────────────────────────
spring.data.mongodb.uri=mongodb://localhost:27017/audit_logs

# ── JWT ──────────────────────────────────────────────────────────────────────
app.jwt.secret=rrKXKmVpFWcgYmqkLfXCUFe1+jeXuZJtvgbpRGn44Sg=
app.jwt.expiration=3600000

app.jwt.refresh-expiration=604800000

# ── Mail (disabled for local dev) ────────────────────────────────────────────
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=abensaid511@gmail.com
spring.mail.password=damd irdw yagb yurq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.test-connection=false
app.mail.from=noreply@tunisietelecom.tn
app.mail.logo-url=https://upload.wikimedia.org/wikipedia/fr/f/f9/LOGO_TT_.jpg
spring.mail.properties.mail.smtp.connectiontimeout=1000
spring.mail.properties.mail.smtp.timeout=1000
# ── File Upload ──────────────────────────────────────────────────────────────
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB
app.upload.dir=uploads/

# ── Frontend URL ─────────────────────────────────────────────────────────────
app.frontend.url=http://localhost:5173

# ── Swagger ──────────────────────────────────────────────────────────────────
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.operationsSorter=method